import os
print('exceptions initialized', __name__)
print(os.getcwd())